### PR TITLE
Fix tests to work with SF5 process package

### PR DESCRIPTION
**Pull request by SpacePossum**
The PR fixes the tests because of the SF5 process API interface changes and updates the code style of some tests.
There are no functional changes to the package itself.

fixes: https://github.com/sebastianbergmann/diff/issues/90
replaces https://github.com/sebastianbergmann/diff/pull/89

### CODE REVIEW

**Comment by SpacePossum** [comment]
the tests on both SF5 https://travis-ci.org/sebastianbergmann/diff/jobs/628781123#L236 and SF4 https://travis-ci.org/sebastianbergmann/diff/jobs/628781120#L280 now pass, :tada:

**Comment by sebastianbergmann** [comment]
This branch has conflicts that must be resolved.

**Comment by GrahamCampbell** [comment]
Looks good, other than the travis conflict. This PR can just be merged without the changes to the travis file, I think?

**Comment by sebastianbergmann** [comment]
I avoid merge commits whenever I can and prefer "rebase and merge" instead. This is not possible right now so a new/updated pull request would be much appreciated.

**Comment by SpacePossum** [comment]
@sebastianbergmann no worries, I've rebased the PR so there are no more conflicts, tests are green as well :+1:

**Pull request merged**
