### PR TITLE
Fix diffToArray to accept array of lines

### LINKED ISSUE #28: Cannot diff two arrays
I am not sure if this is a bug or if it is just unclear documentation.

The doc comments would lead one to believe that you can take the diff of two arrays. However in diffToArray the first thing that happens is the $from arg is passed as the second arg to preg_match_all which only takes a string for the second argumet making it so that this has to be an array.

The readme mentions nothing about arrays, so like I said, may just need to be reflected correctly in the phpdocs.

### PR DESCRIPTION
**Pull request by ThatIsGeek**
Resolves #28

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Is the encoding of `DifferTest.php` correct, because github thinks it's a binary file?

**Comment by ThatIsGeek** [comment]
The encoding is correct, but there are NUL bytes. I replaced them with \0.

**Comment by steffkes** [comment]
@sebastianbergmann any reasons to not merge this PR? `diff` as well as `diffToArray` suggest `array|string` in their doc block for `$from` and `$to` which obviously is not really the case :/

**Comment by nochso** [comment]
Fyi, I've worked on a [fork](https://github.com/nochso/diff) in a different namespace. Issue was [fixed here](https://github.com/nochso/diff/commit/e4c0dd1ab3b0f83d65f4138e5b810ea81b47f9a3). Otherwise some refactoring and working with a Formatter interface.

(Sorry, I'm not sure about the etiquette when it comes to forking and diverting..)

**Comment by sebastianbergmann** [comment]
I am sorry for dropping the ball on this. This branch now has conflicts that must be resolved. Please open a new pull request. Thanks!

**Pull request closed without merging**
