### PR TITLE
Clean up the test suit

### PR DESCRIPTION
**Pull request by SpacePossum**
Sadly, after the release of v2 not all are happy with it.
I'm sorry and hereby apologize to everyone who is effected by the changes.

The intent for v2 was to provide an extendable `diff` library together with some issue resolving which required BC breaks.
However some changes were not up to par and need work.

This PR is the start of resolving the reported issue.
First of I want to create a nice and clean test suite for the package such that new changes can be reviewed more easy.

The changes are:
- Exception - Move to own namespace. (I'm still puzzled why this worked with PSR4)
- UnitTest - Code grooming.
   - move test to own namespace
   - break up `DifferTest` to dedicated test per class

To be clear, besides the namespace change of the Exceptions, there are no functional changes to the package in this PR (only to its tests).

Ping @keradus if you've time please do a sanity check :)

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
* I do not use PSR-4 (or similar) for my components
* Please use classmap-based autoloading
* Please do not put exceptions into a separate namespace

**Comment by SpacePossum** [comment]
>I do not use PSR-4 (or similar) for my components
>Please use classmap-based autoloading
>Please do not put exceptions into a separate namespace

all done (I think)

**Comment by sebastianbergmann** [comment]
Please keep test case classes in the same namespace as the class they're testing.

**Comment by SpacePossum** [comment]
>Please keep test case classes in the same namespace as the class they're testing.

updated

**Comment by sebastianbergmann** [comment]
Thanks for your quick responses.

Is this ready to be merged?

**Comment by SpacePossum** [comment]
Squashed to get a clean commit for the changes, if the tests are green it should be good. 
However I'm not sure why the coverage report comes back so poorly.

**Comment by SpacePossum** [comment]
:+1:  thanks :)

**Pull request merged**
