### PR TITLE
Fix edge cases / Improve mem. usage

### PR DESCRIPTION
**Pull request by SpacePossum**
- Remove reference mismatch on finding same ending of array.
- Do not crash on undefined var. on PHP7
- More tests

Tagged as WIP as some cases still are missing test coverage, but I would like Travis to report on the work so far.
After this enough groundwork is done to start adding line numbers.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Not sure that support for old versions of PHP and PHPUnit needs to be kept. What's keeping us from bumping the major version and removing support for PHP 5.3-5.6 and PHPUnit < 6.

**Comment by SpacePossum** [comment]
More than happy to bump to PHP7 and PHPUnit 6 :)
Therefor I propose to wrap up this one on the current 1.x, giving the current users stuck on PHP > 7 the optimization and bug fixes on the current code.

Than I work on adding the line numbers; I've played around with it and one way or the other it would require a BC break. Maybe it would be nice to (after this PR) add the line numbers and bump to PHP7 & PHPUnit 6 and by that start working on a 2.x release of the `diff`. WDYT?

**Comment by sebastianbergmann** [comment]
Lets get this merged first and then we'll see. Let me know when this is ready to be merged.

**Comment by SpacePossum** [comment]
I think this one is ready :)

**Pull request merged**
