### PR TITLE
Fix Parser to support empty start and end of chunks

### PR DESCRIPTION
**Pull request by demerzel3**

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
The tests you added fail. Could you have a look at that? Thanks!

**Comment by demerzel3** [comment]
I don't understand why they are failing on travis, if I run `vendor/bin/phpunit tests` locally everything seems fine.

**Comment by sebastianbergmann** [comment]
Weird. I, too, can run them just fine locally:
```
PHPUnit 5.2.9 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.3 with Xdebug 2.4.0RC4
Configuration: /usr/local/src/diff/phpunit.xml.dist

................................................                  48 / 48 (100%)

Time: 10.96 seconds, Memory: 65.10Mb

OK (48 tests, 118 assertions)
```

**Comment by sebastianbergmann** [comment]
Sorry for dropping the ball on this over a year ago. I wanted to merge this just now and ran into the following issue:

```
PHPUnit 6.1.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.5 with Xdebug 2.5.3
Configuration: /usr/local/src/diff/phpunit.xml

..............................................FF                  48 / 48 (100%)

Time: 8.07 seconds, Memory: 65.10MB

There were 2 failures:

1) SebastianBergmann\Diff\ParserTest::testParseChunkWithEmptyStart
Failed asserting that actual size 1 matches expected size 2.

/usr/local/src/diff/tests/ParserTest.php:87

2) SebastianBergmann\Diff\ParserTest::testParseChunkWithEmptyEnd
Failed asserting that actual size 1 matches expected size 2.

/usr/local/src/diff/tests/ParserTest.php:108

FAILURES!
Tests: 48, Assertions: 118, Failures: 2.
```

Can you please have a look? Thanks!

**Comment by sebastianbergmann** [comment]
This branch has conflicts that must be resolved. Please open a new pull request against current `master`. Thank you.

**Pull request closed without merging**
