### PR TITLE
Update Differ.php for IDE Helper to work

### PR DESCRIPTION
**Pull request by markusramsak**
has to be nullable for \IdeHelper\Test\TestCase\Annotator\DiffHelperTrait to work $differ = new Differ(null);

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it.

**Comment by markusramsak** [comment]
> Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it.

why? It solves current issues with two libraries.

**Comment by SpacePossum** [comment]
@markusramsak  likely the `DiffHelperTrait` needs updating and not this package, can you describe where this `DiffHelperTrait` comes from? (like which project, or something, I didn't find in this project nor in PHPUnit itself)

**Comment by markusramsak** [comment]
I think you are right that the better solution is to patch the other libraries like 
https://github.com/dereuromark/cakephp-ide-helper
they use `new Differ(null)` which they should/could change to `new Differ(new DiffOnlyOutputBuilder())`

**Pull request closed without merging**
